[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Route API requests to Netlify Serverless Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Route all web pages to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200